### ISSUE TITLE
How to load a saved model into Keras, not tf.Keras

### ISSUE THREAD

**Issue by jamescook106** [plumerai/larq#83]
How to load a saved model into Keras, not tf.Keras. Would be good to add this to documentation or to provide an example, as is not immediately obvious how to do it.

**Comment by lgeiger** [comment]
Keras and `tf.keras` are two independent implementations of the Keras API. We opted to rely on `tf.keras` for better support of the TensorFlow ecosystem (e.g. `tf.data`, multi GPU training, TensorFlow 2.0, ...). For more details see https://stackoverflow.com/a/54117754

Mixing Keras and `tf.keras` code in one script is not possible. Therefor loading our layers as [custom objects](https://www.tensorflow.org/api_docs/python/tf/keras/utils/custom_object_scope) into Keras won't work since we rely on `tf.keras` under the hood.

For simple external function that rely on Keras and cannot be changed (e.g. because they are in a module) the only way of I can think of is to mock the Keras import and replace it with `tf.keras`. To try this add
```python
import sys
import tensorflow as tf
sys.modules["keras"] = tf.keras
```
to the very top of your script.

⚠️ ⚠️ ⚠️ 💥 **Note:** This solution may break in very weird and unexpected ways if the external Keras code relies on Keras internals, uses deprecated methods, or does anything non-standard. Therefor this should only be used for very early experimentation and not for anything remotely serious!
